pipeline {
    agent any
    tools {
      maven 'maven3'
    }
    environment {
      DOCKER_TAG = getVersion()
    }
    stages {
        stage('SCM') {
            steps {
                git 'https://github.com/javahometech/dockeransiblejenkins'
            }
        }
        stage('Maven Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Docker Build') {
            steps {
                sh "docker build . -t andrei56063/study:${DOCKER_TAG} "
            }
        }
        stage('DockerHub Push') {
            steps {
                withCredentials([string(credentialsId: 'docker-hub', variable: 'dockerHubPassword')]) {
                    sh "docker login -u andrei56063 -p ${dockerHubPassword}"
                }

                sh "docker push andrei56063/study:${DOCKER_TAG} "
            }
        }
    }
}

def getVersion() {
    def commitHash = sh label: '', returnStdout: true, script: 'git rev-parse --short HEAD'
    return commitHash
}

